# -*- coding: utf-8 -*-
"""assignment_22_am.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWdVJ6kXqbNjpssyqxntrvYkh-b9yViW

part-a
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv")

print(df.shape)   # should be > 50,000 rows
df.head()

print(df.loc[0:4, ['carat', 'price']])
print(df.loc[10:15, ['cut', 'color']])
print(df.loc[:, ['price']])

print(df.iloc[0:5, 0:2])
print(df.iloc[10:20, 2:5])
print(df.iloc[0])

df[(df['price'] > 5000) & (df['carat'] > 1)]
df[df['cut'] == 'Premium']
df[df['price'] > 10000]

df.describe()

plt.hist(df['price'], bins=30)
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.title("Price Distribution")
plt.show()

sns.barplot(x='cut', y='price', data=df)
plt.title("Average Price by Cut")
plt.show()

df['price'].head(100).plot()
plt.xlabel("Index")
plt.ylabel("Price")
plt.title("Price Trend")
plt.show()

sns.kdeplot(df['price'])
plt.title("Density Plot")
plt.show()

"""part-b"""

grouped = df.groupby('cut')['price'].mean()
grouped

grouped.plot(kind='bar')
plt.xlabel("Cut")
plt.ylabel("Average Price")
plt.title("Average Price by Cut")
plt.show()

df[['carat', 'price']].head(100).plot()
plt.title("Carat vs Price Trend")
plt.show()

sns.kdeplot(df['carat'], label='Carat')
sns.kdeplot(df['price'], label='Price')
plt.legend()
plt.title("Carat vs Price Distribution")
plt.show()

"""part-c"""

avg_price = df['price'].mean()
df[df['price'] > avg_price]

import pandas as pd

df = pd.read_csv("data.csv")

filtered = df[df['price'] > 5000]

df.head()

df.describe()

filtered = df[df['price'] > 5000]
filtered

import matplotlib.pyplot as plt

plt.hist(df['price'])
plt.title("Price Distribution")
plt.show()

df['price'].plot()
plt.title("Price Trend")
plt.show()



