# -*- coding: utf-8 -*-
"""assignment_22_pm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_57fl8FGGJIZMfoiXTyQLcTaJWHUTedR

part-a
"""

import pandas as pd

# Load dataset
df = pd.read_csv("data.csv")

# Display first rows
print(df.head())

# Check missing values
print(df.isnull().sum())

# Handle missing values
df = df.dropna()   # or df.fillna(method='ffill')

# Feature selection
df = df[['Age', 'Salary', 'Purchase_Amount', 'Category']]

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Features & target
X = df[['Age', 'Salary']]
y = df['Purchase_Amount']

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
model = LinearRegression()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Encode categorical target
le = LabelEncoder()
df['Category'] = le.fit_transform(df['Category'])

# Features & target
X = df[['Age', 'Salary']]
y = df['Category']

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

# Prediction
y_pred = clf.predict(X_test)

# Evaluation
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

"""part-b"""

import pandas as pd

df = pd.read_csv("data.csv")

# Group by Category and calculate mean Purchase_Amount
grouped = df.groupby("Category")["Purchase_Amount"].mean()

print(grouped)

import matplotlib.pyplot as plt

grouped.plot(kind='bar')

plt.title("Average Purchase Amount by Category")
plt.xlabel("Category")
plt.ylabel("Average Purchase Amount")

plt.show()

df_sorted = df.sort_values(by="Age")

plt.plot(df_sorted["Age"], df_sorted["Purchase_Amount"])

plt.title("Age vs Purchase Amount")
plt.xlabel("Age")
plt.ylabel("Purchase Amount")

plt.show()

df["Age"].plot(kind='kde', label="Age")
df["Purchase_Amount"].plot(kind='kde', label="Purchase Amount")

plt.legend()
plt.title("Distribution Comparison")

plt.show()

"""part-c"""

df = pd.read_csv("data.csv")

avg = df["Salary"].mean()

filtered = df[df["Salary"] > avg]

print(filtered.head())

df.describe()

"""part-d"""

import pandas as pd
df = pd.read_csv("data.csv")

df.head()
df.info()

df = df.dropna()

df.describe()

df.groupby("Category")["Purchase_Amount"].mean()

import matplotlib.pyplot as plt

df.groupby("Category")["Purchase_Amount"].mean().plot(kind='bar')
plt.show()

plt.plot(df["Age"], df["Purchase_Amount"])
plt.show()